spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mydb?createDatabaseIfNotExist=true
    username: admin
    password: adminadmin
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExp: 600 #5m
    refreshTokenExp: 1800 #10m
  flyway:
    enabled: true
    locations: classpath:db/migration