server:
  port: 8080
management:
    endpoints:
      web:
        exposure:
          include: metrics
spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mydb?createDatabaseIfNotExist=true
    username: admin
    password: adminadmin
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExp: 600 #5m
    refreshTokenExp: 86400 #1 Day
  flyway:
    enabled: true
    locations: classpath:db/migration
otel:
  instrumentation:
    micrometer:
      enabled: true
  service:
    name: "store"
  exporter:
    otlp:
      endpoint: "http://localhost:4318"
      logging:
        enabled: true
      metrics:
        enabled: true
      traces:
        enabled: true